<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Introduction to NumPy

_Authors: Hank Butler (ATX), James Hampton (SEA)_


In [1]:
import numpy as np

In [2]:
import numpy as whatever_hank_feels_like

In [3]:
import numpy as np

____

## Address Students: Initial check for understanding

Students should be able to explain what the first line of code did.

Import does what? Telling Python to load an external module/library

What is NumPY? Numerical Python, used for arrays/array aggregations and calculations, etc.

What is the "as np" doing? Importing numpy under the alias np. Flesh out why we do this!

We imported the library NumPy (short for 'Numerical Python') and gave it the alias 'np'

____

# Learning Objectives

## By the end of this lesson you should be able to:

- Understand what an array is and why it's important
- Create an array in NumPy
- Perform operations and aggregations on arrays:
    - Loops
    - Slicing
    - Aggregations
    - Array Arithmetic (MATH)


# Table of Contents

#### 0. Definition + Purpose of an ndarray
    - rectangular array of numbers (rows + columns, tabular data)
    - slowness of loops
    - built on C which is faster than python
    - data types
    
#### 1. Creating arrays
    - from lists (and nested lists)
    - np.ones, np.zeros, np.linspace
    - np.random

#### 2. Array attributes
    - dtype
    - size
    - shape
    
#### 3. Array Computations
    - arithmetic operations (+, -, x, /)
    - numpy operations (np.square, np.sin, np.cos)
    - aggregating functions (.mean, .median, .unique + np. versions)

#### 4. Array Slicing and Ordering
    - slicing
    - boolean arrays / conditions
    - sorting arrays
    

___

## 0. Definition + Purpose of Arrays

    - rectangular array of numbers
    - Slowness of Loops, Speed
    - Built on C, faster than Python
    - Data Types
    
___

### Rectangular Array of Numbers

- Helps to think of all data fundamentally as an array of numbers
- What do I mean by an array?
    - A matrix in two-dimensions (rows x columns)
- Slowness:
    - Efficient storage and manipulation of data is a fundamental part of data science
    - Python is built on-top of C. What do I mean by this?
- Data Types:
    - NumPy Arrays are similar to Python Lists, but provide more efficient storage.




In [4]:
# Display built-in documentation (pop up window)

np?

Type:        module
String form: <module 'numpy' from '/Users/henrybutler/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
File:        ~/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>

# Arrays in NumPy

NumPy arrays can be built in lots of ways (more on this later), but the most basic arrays can be built from simple lists

In [5]:
# One-dimensional arrays are written with lowercase variables
a = [1, 2, 3]

a_arr = np.array(a)

a_arr

array([1, 2, 3])

In [7]:
# Arrays have some important attributes
print(f'Shape: {a_arr.shape}') # How the entries are arranged
print(f'Size: {a_arr.size}') # How many entires
print(f'dtype: {a_arr.dtype}') # What type of data are the entries

Shape: (3,)
Size: 3
dtype: int64


In [8]:
# Multidimensional arrays are lists of lists and are written with capital variables
X = [[1, 2, 3], [4, 5, 6]]

X_arr = np.array(X)

X_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# Arrays have some important attributes
print(f'Shape: {X_arr.shape}') # How the entries are arranged
print(f'Size: {X_arr.size}') # How many entires
print(f'dtype: {X_arr.dtype}') # What type of data are the entries

Shape: (2, 3)
Size: 6
dtype: int64


Notice that our shape `(2, 3)` is now a tuple of length **2**. This is because our array `X` has **2** rows and **3** columns, and so has two dimensions (rows and columns).

In [10]:
# A complicated example
# ALL sublists must be the same length (in this case, length 3)
Y = [
    [[1.1, 2.3, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
]

Y_arr = np.array(Y)

Y_arr

array([[[ 1.1,  2.3,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 7. ,  8. ,  9. ],
        [10. , 11. , 12. ]]])

In [11]:
# Arrays have some important attributes
print(f'Shape: {Y_arr.shape}') # How the entries are arranged
print(f'Size: {Y_arr.size}') # How many entires
print(f'dtype: {Y_arr.dtype}') # What type of data are the entries

Shape: (2, 2, 3)
Size: 12
dtype: float64


Our array now has **3** dimensions--our shape tuple `(2,2,3)` is length **3**.

**Nearly all** of the arrays we will use will be **two dimensional** (rows and columns, i.e. "tabular data"). So don't worry too much about 3dim or higher-dim arrays for now.

----
### PRACTICE

Create a one-dimensional array with your own values

Create a two-dimensional array with your own values

- Note: you can start with a list then convert it to an array
----

In [13]:
a = np.array([1, 2, 3])

B = np.array([[4, 5, 6], [7, 8, 9]])

print(a)
print(B)

[1 2 3]
[[4 5 6]
 [7 8 9]]


# Array Computation

This is the **bread and butter** of NumPy. The entire reason NumPy exists is because it can perform these mathematical operations **with X-TREME efficiency**.

## Arrays And Single Values

In [15]:
# We can use standard Python arithmetic operations on numpy arrays
X_one_dim = np.array([1, 2, 3, 4])

X_two_dim = np.array([[1, 2, 3], [4, 5, 6]])


In [16]:
# Using a math operation with a single value "broadcasts" the operation to EACH ELEMENT in the array
print(X_one_dim)
print(X_one_dim + 5)

[1 2 3 4]
[6 7 8 9]


In [17]:
print(X_two_dim)
print(X_two_dim ** 2)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [18]:
# Can also do modulo
print(X_one_dim)
print(X_one_dim % 2)

[1 2 3 4]
[1 0 1 0]


In [19]:
print(X_two_dim)
print(X_two_dim / 10)

[[1 2 3]
 [4 5 6]]
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


----
### PRACTICE

1. Create an array from 1 to 10 (INCLUSIVE!) with `np.arange`

2. Add 2 to each element in your array

3. Multiply each element by 4

4. Subtract 5 from each element

5. Divide each element by 3

6. Divide each element by 2 using floor division

----

In [22]:
###---SOLUTION---###


x = np.arange(1, 11)
# x
print("1: ", x)
print("2: ", x + 2)
print("3: ", 4 * x)
print("4: ", x - 5)
print("5: ", x / 3)
print("6: ", x // 2)


1:  [ 1  2  3  4  5  6  7  8  9 10]
2:  [ 3  4  5  6  7  8  9 10 11 12]
3:  [ 4  8 12 16 20 24 28 32 36 40]
4:  [-4 -3 -2 -1  0  1  2  3  4  5]
5:  [0.33333333 0.66666667 1.         1.33333333 1.66666667 2.
 2.33333333 2.66666667 3.         3.33333333]
6:  [0 1 1 2 2 3 3 4 4 5]


## Arrays of Equal Size
Operations between arrays of equal size are done component-wise

In [23]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(f'x: {x}')
print(f'y: {y}')

x + y

x: [1 2 3]
y: [4 5 6]


array([5, 7, 9])

In [24]:
x * y

array([ 4, 10, 18])

----
### PRACTICE

With `X = np.array([[1,1], [2, 2]])` and `Y = np.array([[1, 2], [1, 2]])`, 

compute:

- `X + Y`
- `X / Y`
----

In [25]:
X = np.array([[1, 2], [2, 2]])
Y = np.array([[1, 2], [1, 2]])

In [26]:
X

array([[1, 2],
       [2, 2]])

In [27]:
Y

array([[1, 2],
       [1, 2]])

In [28]:
# Shuya's Code

X = np.array([[1,1], [2, 2]])
Y = np.array([[1, 2], [1, 2]])

print('addition: ', X + Y)
print('division: ', X / Y)



addition:  [[2 3]
 [3 4]]
division:  [[1.  0.5]
 [2.  1. ]]


## Summary Statistics and Aggregate functions

NumPy will calculate means and standard deviations for us!

In [29]:
data = np.array([1, 2, 3, 4, 5])

print(data)
print(data.mean())
print(data.std())

[1 2 3 4 5]
3.0
1.4142135623730951


In [30]:
np.mean(data)

3.0

In [31]:
np.std(data)

1.4142135623730951

In [32]:
# Two dimensions
data = np.array([[1, 2], [1, 2]])

print(data)

[[1 2]
 [1 2]]


In [33]:
# Column mean
print(data.mean(axis = 0))
# Column Std
print(data.std(axis = 0))

[1. 2.]
[0. 0.]


In [34]:
# Row means
print(data.mean(axis = 1))
# Row Std
print(data.std(axis = 1))

[1.5 1.5]
[0.5 0.5]


In [35]:
# Entire matrix mean
print(data.mean())
# entire matrix std
print(data.std())

1.5
0.5


NumPy can also compute sums:

In [36]:
print(X)

[[1 1]
 [2 2]]


In [37]:
X.sum(axis = 0)

array([3, 3])

In [38]:
X.sum(axis = 1)

array([2, 4])

In [39]:
X.sum()

6

# Slicing Arrays

Each dimension of an array behaves a lot like a Python list

In [41]:
X = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [42]:
X.shape

(4, 5)

In [43]:
X[0, 0]

1

In [44]:
X[0][0]

1

In [45]:
# Third row, fourth column

X[2, 3]

14

In [46]:
# First three rows, all cols

X[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [47]:
# All rows, 3rd col onward

X[:, 2:]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [49]:
X[:2,3:]

array([[ 4,  5],
       [ 9, 10]])

----
### PRACTICE

Use indexing on `X = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12, 13, 14, 15], [16, 17, 18, 19, 20]])` to:

- Get `10` from X
- Get only the 2nd column of X
- Get the second and third rows, along with the first and second columns, of X
----

In [50]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [51]:
# Solutions
X[1, 4]

10

In [52]:
X[1, -1]

10

In [53]:
X[:, 1]

array([ 2,  7, 12, 17])

In [54]:
X[1:3, 0:2]

array([[ 6,  7],
       [11, 12]])

# Intermediate NumPy

## Creating Arrays Automatically

In [55]:
# An array of all 0s
X = np.zeros((3, 4))

X

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
X.shape

(3, 4)

In [57]:
# An array of all 1s
X = np.ones((3, 3))

X

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
# An array of all the same value
X = np.full((3, 4), np.pi)

X

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

One particular kind of array-creation is especially important: **ranges**.  Creating ranges in NumPy is similar to how we've seen ranges in Python.

In [59]:
# From start to stop - 1
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# Step through by 2s
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [61]:
# Create a range of evenly-spaced values from START to STOP
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [62]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [63]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [64]:
np.linspace(0, 10, 100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

`np.linspace` is going to be very helpful later in the course when we begin performing Gridsearch on model hyperparameters. 

**You will understand all of these terms in a few weeks!**

----
### PRACTICE

1. Create an array of 10 values, evenly spaced between 0 and 100
- Hint: Use np.linspace()

2. Create a 3x3 array of all zeros

3. Create an 2x4 array of your favorite number
----

In [65]:
### --- SOLUTION --- ###
print("1: ")
np.linspace(0, 100, 10)

1: 


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [66]:
print("2: ")
np.zeros((3, 3))

2: 


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [67]:
print("3: ")
np.full((2, 4), 42)

3: 


array([[42, 42, 42, 42],
       [42, 42, 42, 42]])

In [68]:
np.full((2, 4), "Hello")

array([['Hello', 'Hello', 'Hello', 'Hello'],
       ['Hello', 'Hello', 'Hello', 'Hello']], dtype='<U5')

In [70]:
ex = np.array([1, 1.1, 2, 2.2])

ex.dtype

dtype('float64')

## Random number generation with NumPy

We can use NumPy to generate **arrays filled with random values**.

In [80]:
# Create a 3x3 array of evenly distributed random values b/w 0 and 1

np.random.random((3, 3))

array([[0.54425209, 0.24486356, 0.52676395],
       [0.8683178 , 0.1280198 , 0.75643299],
       [0.78609709, 0.20803373, 0.16226167]])

In [81]:
# Create a 3x3 array of normally distributed (bell-curve) random values
# with mean 0 and std dev 1

np.random.normal(0, 1, (3, 3))

array([[ 1.72243949, -0.32070073, -0.42708883],
       [-0.73414852,  0.34685908,  1.00002054],
       [ 1.15939985, -1.29464958, -0.43601955]])

In [82]:
#3x3 array of random integers from the interval [0, 10]

np.random.randint(0, 10, (3, 3))

array([[5, 7, 5],
       [7, 6, 1],
       [4, 9, 5]])

## Special Values in NumPY

### np.nan

Stands for **"not a number"**

Commonly used to represent **missing values.**

This will appear later in Pandas (as NaN)

In [83]:
np.nan

nan

In [84]:
# NaN doesn't like to cooperate with numbers
2 + np.nan

nan

In [85]:
np.nan ** 2

nan

### np.inf

'infinity'

Good for when you want to do a comparison that you want to fail or succeed.

EG. set your max value to np.inf and any number will be less than your max value.

In [86]:
np.inf

inf

In [87]:
9999999999999999 < np.inf

True

In [88]:
-9999999999999999 > -np.inf

True

In [89]:
# Check if element in array is pos or neg inf
a = np.array([1, 0, np.nan, np.inf])

print('Is infinity in a?')
print(np.isinf(a))

print('Is nan in a?')
print(np.isnan(a))


Is infinity in a?
[False False False  True]
Is nan in a?
[False False  True False]


## Intermediate Numpy Slicing

You can slice NumPy arrays using _boolean masks_. We'll go through some simple examples here.

In [90]:
x = np.array([1, 2, 3, 4, 5])

# Some condition

less_than_three_mask = x < 3

# A boolean array

less_than_three_mask

array([ True,  True, False, False, False])

In [91]:
# Mask out the Falses
x[less_than_three_mask]

array([1, 2])

In [92]:
# Any boolean condition works
even_mask = x % 2 == 0

# Equivalent to x[x % 2 == 0]

x[even_mask]

array([2, 4])

In [93]:
x[less_than_three_mask & even_mask]

array([2])

In [94]:
# For one-liners, conditions must be separated by parentheses
x[(x < 3) & (x % 2 == 0)]

array([2])

In [95]:
x[x < 3 & x % 2 == 0]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [96]:
x[less_than_three_mask | even_mask]

array([1, 2, 4])

In [97]:
x.dtype

dtype('int64')

In [99]:
for i in x:
    print(i.dtype)
    print(type(x))

int64
<class 'numpy.ndarray'>
int64
<class 'numpy.ndarray'>
int64
<class 'numpy.ndarray'>
int64
<class 'numpy.ndarray'>
int64
<class 'numpy.ndarray'>


## Intermediate NumPy functions

NumPy has efficient implementations of standard arithmetic operations (multiplication, addition, epxonentation, division). It also gives us access to some useful math functions

In [100]:
# Absolute value
x = np.arange(-5, 6)
print(x)
np.abs(x)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]


array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4, 5])

In [101]:
# Trigonometric Functions
# Also cos and tan
x = np.arange(-2, 3)
print(x)
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

[-2 -1  0  1  2]
[-0.90929743 -0.84147098  0.          0.84147098  0.90929743]
[-0.41614684  0.54030231  1.          0.54030231 -0.41614684]
[ 2.18503986 -1.55740772  0.          1.55740772 -2.18503986]


In [102]:
# Logs
x = np.array([1, 2, 3])
# Values must be strictly positive (greater than 0)
np.log(x)

array([0.        , 0.69314718, 1.09861229])

In [103]:
np.log(-1)

<ipython-input-103-0cd3490738d5>:1: RuntimeWarning: invalid value encountered in log
  np.log(-1)


nan

In [104]:
# exponents -- 2 ** x, 3 ** x
x = np.array([0, 1, 2, 3])

print(x)
np.exp(x)

[0 1 2 3]


array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

### Exponents and Logs

In [105]:
#Inverse of exponentials are called logarithms, np.log gives you basic natural log

x = [1, 2, 4, 10]

print("x         = ", x)
print("ln(x)     = ", np.log(x))
print("log2(x)   = ", np.log2(x))
print("log10(x)  = ", np.log10(x))

x         =  [1, 2, 4, 10]
ln(x)     =  [0.         0.69314718 1.38629436 2.30258509]
log2(x)   =  [0.         1.         2.         3.32192809]
log10(x)  =  [0.         0.30103    0.60205999 1.        ]


### Aggregate Functions

In [106]:
#Calling .reduce on .add returns the sum of all elements
x = np.arange(1, 6)

np.add.reduce(x)

15

In [107]:
#Callling .reduce on .multiply results in product of all elements
np.multiply.reduce(x)

120

In [108]:
L = np.random.random(100)

np.sum(L)

49.32584620947521

In [110]:
# Show you how much faster arrays are

big_array = np.random.rand(1000000)

%timeit sum(big_array)
%timeit np.sum(big_array)

81 ms ± 111 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
207 µs ± 1.27 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Other useful agg functions

- np.std => std deviation
- np.mean => mean of elements
- np.var => compute variance
- np.median => compute median
- np.percentile => compute rank-based stats of elements
- np.any => evaluate whether any elements are true
- np.all => evaluate whether all elements are true

---

## 4. Slicing, Ordering, Comparison Operators

---

### Slicing

In [111]:
x = np.arange(10)

x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Basically same as slicing we did with lists

In [112]:
x[:5]

array([0, 1, 2, 3, 4])

In [113]:
x[5:]

array([5, 6, 7, 8, 9])

In [114]:
x[-1]

9

In [115]:
x[3:5]

array([3, 4])

In [116]:
# 2-dimensional array
Y = np.random.randint(0, 10, (3, 3))

Y

array([[4, 7, 3],
       [2, 6, 9],
       [6, 5, 5]])

In [117]:
# Slice Second Row
Y[1]

array([2, 6, 9])

In [118]:
Y[1][1]

6

In [119]:
Y[-1][-1]

5

### comparison operators / boolean arrays

In [120]:
x = np.array([1, 2, 3, 4, 5])

x

array([1, 2, 3, 4, 5])

In [121]:
x < 3

array([ True,  True, False, False, False])

In [122]:
x > 3

array([False, False, False,  True,  True])

In [123]:
x <= 3

array([ True,  True,  True, False, False])

In [124]:
x >= 3

array([False, False,  True,  True,  True])

In [125]:
x != 3

array([ True,  True, False,  True,  True])

In [126]:
x == 3

array([False, False,  True, False, False])

In [141]:
# Two dimensional example
rng = np.random.RandomState(0)

x = rng.randint(10, size = (3, 4))

x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [142]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [143]:
# Counting entries
np.count_nonzero(x < 6)

8

In [ ]:
#Boolean arrays and masks



### Sorting Arrays

In [144]:
x = np.array([2, 1, 4, 3, 5])

np.sort(x)

array([1, 2, 3, 4, 5])

In [145]:
x.sort()
print(x)

[1 2 3 4 5]


In [150]:
# Sorting rows / columns

rand = np.random.RandomState(42)

X = rand.randint(0, 10, (4, 6))

X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [151]:
# Sort Each Column of X
np.sort(X, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [152]:
#sort each row of X
np.sort(X, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

### Reshaping Arrays

In [153]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
#-1 automatically decides the number of cols

reshaped = arr.reshape(2, -1)

In [155]:
reshaped

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

---

In [156]:
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)

print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [157]:
np.concatenate([a, b], axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [158]:
np.hstack([a, b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])